filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
      - /logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
