filebeat.inputs:
  - type: filestream
    id: mocklogs
    enabled: true
    paths:
      - /logs/*.log
      - /logs/*.json
    prospector.scanner.check_interval: 10s
    close.on_state_change.inactive: 5m
    close.reader.after_interval: 10m
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
    backoff.init: 1s
    backoff.max: 10s
    max_backoff: 10s
    backoff.factor: 2
    clean_inactive: 24h
    ignore_older: 72h

filebeat.registry.flush: 5s
filebeat.registry.file_permissions: 0600

monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

output.logstash:
  hosts: ["logstash:5044"]
  bulk_max_size: 2048
  worker: 2
  compression_level: 4
  loadbalance: true
  pipelining: 128
  timeout: 30s
  slow_start: false

queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s

logging.level: info
logging.metrics.enabled: false
